changelog:
  exclude:
    labels:
      - skip-changelog
      - ignore-for-release
  categories:
    - title: "Breaking Changes"
      labels:
        - breaking-change
        - semver-major
    - title: "Features"
      labels:
        - feature
        - enhancement
        - semver-minor
    - title: "Fixes"
      labels:
        - bug
        - fix
    - title: "Documentation"
      labels:
        - documentation
        - docs
    - title: "Maintenance"
      labels:
        - chore
        - refactor
        - dependencies
    - title: "Other Changes"
      labels:
        - "*"
