import type { NamingStrategy } from "@schema-transformation-toolkit/core";
import { createNamingStrategy } from "@schema-transformation-toolkit/core";

const RESERVED_WORDS = [
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "enum",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "function",
  "if",
  "import",
  "in",
  "instanceof",
  "new",
  "null",
  "return",
  "super",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "var",
  "void",
  "while",
  "with",
  "as",
  "implements",
  "interface",
  "let",
  "package",
  "private",
  "protected",
  "public",
  "static",
  "yield",
  "any",
  "boolean",
  "constructor",
  "declare",
  "get",
  "module",
  "require",
  "number",
  "set",
  "string",
  "symbol",
  "type",
  "from",
  "of",
] as const;

export function createZodNamingStrategy(): NamingStrategy {
  return createNamingStrategy({
    typeName: {
      style: "pascal",
      emptyFallback: "GeneratedType",
      invalidPrefix: "_",
      reservedWords: [...RESERVED_WORDS],
      reservedWordHandling: "suffix",
      reservedWordSuffix: "_",
    },
    fieldName: {
      style: "camel",
      fallback: "quoted",
      invalidPrefix: "_",
      reservedWords: [...RESERVED_WORDS],
      reservedWordHandling: "suffix",
      reservedWordSuffix: "_",
    },
  });
}
