export type {
  ConversionCapabilityRequirement,
  EntryIrKind,
  ConversionIrPreference,
  ConversionIrSelection,
  ConversionEntrySelection,
  ConversionLossHotspot,
  ConversionPolicyDecision,
  ConversionReport,
  ConversionSemanticCaveat,
  ConversionCapability,
  GeneratorCapabilities,
  OverlayIrKind,
  GeneratorAnalysisHooks,
  ParserCapabilities,
  ConversionRoute,
  ConversionRouteCapabilities,
  IrKind,
  PipelineStage,
  PipelineStageKind,
  SemanticLoss,
  SemanticLossPhase,
  SemanticLossAnalysisContext,
} from "./contracts.js";
export type {
  DescriptorVersion,
  GeneratorDescriptor,
  GeneratorExecutionContext,
  ParserDescriptor,
  ParserExecutionContext,
} from "../schema/contracts.js";
